<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
		<WindowsSdkPackageVersion>10.0.26100.75</WindowsSdkPackageVersion>
		<AssemblyName>Sound Reaver</AssemblyName>
		<RootNamespace>Sungaila.SoundReaver</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Version>1.2.1</Version>
		<ApplicationIcon>App.ico</ApplicationIcon>
		<EnableProfileGuidedOptimization>true</EnableProfileGuidedOptimization>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<!-- C# compiler -->
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<Features>strict</Features>
		<NoWarn>IL2026</NoWarn>
	</PropertyGroup>

	<!-- Debug builds -->
	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<VersionSuffix>debug</VersionSuffix>
		<PackageCertificateThumbprint></PackageCertificateThumbprint>
		<PackageCertificateKeyFile>SoundReaver_TemporaryKey.pfx</PackageCertificateKeyFile>
	</PropertyGroup>

	<!-- Release builds -->
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<SignAssembly>true</SignAssembly>
		<Optimize>true</Optimize>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<PackageCertificateThumbprint>CDCA5E05E8254B26FD0FE56A95222FCD7CC2D0EE</PackageCertificateThumbprint>
	</PropertyGroup>

	<!-- Trimming & AOT options -->
	<PropertyGroup>
		<TrimMode>full</TrimMode>
		<DebuggerSupport>false</DebuggerSupport>
		<EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
		<StackTraceSupport>false</StackTraceSupport>
		<UseSystemResourceKeys>true</UseSystemResourceKeys>
		<XmlResolverIsNetworkingEnabledByDefault>false</XmlResolverIsNetworkingEnabledByDefault>
		<_AggressiveAttributeTrimming>true</_AggressiveAttributeTrimming>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<OptimizationPreference>Size</OptimizationPreference>
		<IlcOptimizationPreference>Size</IlcOptimizationPreference>
		<InvariantGlobalization>false</InvariantGlobalization>
		<MetricsSupport>false</MetricsSupport>
		<EventSourceSupport>false</EventSourceSupport>
		<MetadataUpdaterSupport>false</MetadataUpdaterSupport>
		<Http3Support>false</Http3Support>
		<UseNativeHttpHandler>true</UseNativeHttpHandler>
		<HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
		<UseSizeOptimizedLinq>true</UseSizeOptimizedLinq>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<CsWinRTAotWarningLevel>2</CsWinRTAotWarningLevel>
		<TrimmerSingleWarn>false</TrimmerSingleWarn>
		<EnableAotAnalyzer>true</EnableAotAnalyzer>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Logos\DrownedAbbey.png" />
		<None Remove="Logos\HumanCitadel.png" />
		<None Remove="Logos\Necropolis.png" />
		<None Remove="Logos\RazielsStronghold.png" />
		<None Remove="Logos\RuinedCity.png" />
		<None Remove="Logos\SarafanTomb.png" />
		<None Remove="Logos\SilencedCathedral.png" />
		<None Remove="Logos\TheLighthouse.png" />
		<None Remove="Logos\Underworld.png" />
		<Content Include="App.ico" CopyToOutputDirectory="Always" Link="Assets\App.ico" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Logos\DrownedAbbey.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Logos\HumanCitadel.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Logos\Necropolis.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Logos\RazielsStronghold.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Logos\RuinedCity.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Logos\SarafanTomb.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Logos\SilencedCathedral.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Logos\TheLighthouse.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Logos\Underworld.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Sounds\raziel-0026.wav">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Sounds\raziel-0062.wav">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Page Update="Resources.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<!-- Publish Properties -->
	<PropertyGroup>
		<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
		<GenerateAppInstallerFile>True</GenerateAppInstallerFile>
		<AppxPackageSigningTimestampServerUrl>http://time.certum.pl</AppxPackageSigningTimestampServerUrl>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
		<AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
		<GenerateTestArtifacts>True</GenerateTestArtifacts>
		<AppxBundle>Never</AppxBundle>
		<HoursBetweenUpdateChecks>168</HoursBetweenUpdateChecks>
		<AppxBundlePlatforms>x86|x64|arm64</AppxBundlePlatforms>
		<WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
		<WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>
		<WindowsAppSdkUndockedRegFreeWinRTInitialize>false</WindowsAppSdkUndockedRegFreeWinRTInitialize>
		<AppInstallerUri>https://github.com/sungaila/SoundReaver/releases/latest/download</AppInstallerUri>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Converters" Version="8.2.251219" />
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.4.0" />
		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.298" PrivateAssets="all" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
		<PackageReference Include="Microsoft.WindowsAppSDK.AI" Version="2.2.3" ExcludeAssets="all" />
		<PackageReference Include="Microsoft.WindowsAppSDK.ML" Version="2.1.70" IncludeAssets="build;buildTransitive" PrivateAssets="all" />
		<PackageReference Include="Microsoft.WindowsAppSDK.Widgets" Version="2.0.5" ExcludeAssets="all" />
		<PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" ExcludeAssets="all" />
	</ItemGroup>

	<Target Name="RemoveWindowsMLRuntimeFromBuildOutput"
        AfterTargets="ResolveReferences"
        BeforeTargets="CopyFilesToOutputDirectory">

		<ItemGroup>
			<ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)"
				Condition="'%(ReferenceCopyLocalPaths.Filename)%(ReferenceCopyLocalPaths.Extension)' == 'onnxruntime.dll'
				Or '%(ReferenceCopyLocalPaths.Filename)%(ReferenceCopyLocalPaths.Extension)' == 'DirectML.dll'
				Or '%(ReferenceCopyLocalPaths.Filename)%(ReferenceCopyLocalPaths.Extension)' == 'Microsoft.Windows.AI.MachineLearning.dll'" />

			<RuntimeCopyLocalItems Remove="@(RuntimeCopyLocalItems)"
				Condition="'%(RuntimeCopyLocalItems.Filename)%(RuntimeCopyLocalItems.Extension)' == 'onnxruntime.dll'
				Or '%(RuntimeCopyLocalItems.Filename)%(RuntimeCopyLocalItems.Extension)' == 'DirectML.dll'
				Or '%(RuntimeCopyLocalItems.Filename)%(RuntimeCopyLocalItems.Extension)' == 'Microsoft.Windows.AI.MachineLearning.dll'" />

			<NativeCopyLocalItems Remove="@(NativeCopyLocalItems)"
				Condition="'%(NativeCopyLocalItems.Filename)%(NativeCopyLocalItems.Extension)' == 'onnxruntime.dll'
				Or '%(NativeCopyLocalItems.Filename)%(NativeCopyLocalItems.Extension)' == 'DirectML.dll'
				Or '%(NativeCopyLocalItems.Filename)%(NativeCopyLocalItems.Extension)' == 'Microsoft.Windows.AI.MachineLearning.dll'" />
		</ItemGroup>
	</Target>

	<Target Name="RemoveWindowsMLRuntimeFromPublishOutput"
        AfterTargets="ComputeFilesToPublish">

		<ItemGroup>
			<ResolvedFileToPublish Remove="@(ResolvedFileToPublish)"
				Condition="'%(ResolvedFileToPublish.Filename)%(ResolvedFileToPublish.Extension)' == 'onnxruntime.dll'
				Or '%(ResolvedFileToPublish.Filename)%(ResolvedFileToPublish.Extension)' == 'DirectML.dll'
				Or '%(ResolvedFileToPublish.Filename)%(ResolvedFileToPublish.Extension)' == 'Microsoft.Windows.AI.MachineLearning.dll'" />
		</ItemGroup>
	</Target>

	<!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>

	<!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>

	<Target Name="RemoveWin2DWindowsMetadataReferenceForPackaging" AfterTargets="CoreCompile" BeforeTargets="GenerateAppxPackageFileMap;ResolvePublishFiles;MakeAppx">
		<ItemGroup>
			<!-- exclude Microsoft.Graphics.Canvas.winmd -->
			<WindowsMetadataReference Remove="@(WindowsMetadataReference)" Condition="'%(WindowsMetadataReference.Filename)' == 'Microsoft.Graphics.Canvas'" />
		</ItemGroup>
	</Target>
</Project>